backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "محصولات"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "نام محصول", name: "title", widget: "string"}
      - {label: "قیمت (تومان)", name: "price", widget: "string"}
      - {label: "تصویر محصول", name: "image", widget: "image"}
      - {label: "توضیحات", name: "body", widget: "markdown"}
